// Explicit lazy imports bound production grammar chunks; Pierre's langs option only preloads them.
const languages = {
	shellscript: () => import("@shikijs/langs/shellscript"),
	c: () => import("@shikijs/langs/c"),
	cpp: () => import("@shikijs/langs/cpp"),
	csharp: () => import("@shikijs/langs/csharp"),
	css: () => import("@shikijs/langs/css"),
	dart: () => import("@shikijs/langs/dart"),
	diff: () => import("@shikijs/langs/diff"),
	docker: () => import("@shikijs/langs/docker"),
	go: () => import("@shikijs/langs/go"),
	graphql: () => import("@shikijs/langs/graphql"),
	html: () => import("@shikijs/langs/html"),
	ini: () => import("@shikijs/langs/ini"),
	java: () => import("@shikijs/langs/java"),
	javascript: () => import("@shikijs/langs/javascript"),
	json: () => import("@shikijs/langs/json"),
	jsonc: () => import("@shikijs/langs/jsonc"),
	jsx: () => import("@shikijs/langs/jsx"),
	kotlin: () => import("@shikijs/langs/kotlin"),
	lua: () => import("@shikijs/langs/lua"),
	make: () => import("@shikijs/langs/make"),
	markdown: () => import("@shikijs/langs/markdown"),
	php: () => import("@shikijs/langs/php"),
	powershell: () => import("@shikijs/langs/powershell"),
	python: () => import("@shikijs/langs/python"),
	ruby: () => import("@shikijs/langs/ruby"),
	rust: () => import("@shikijs/langs/rust"),
	scss: () => import("@shikijs/langs/scss"),
	sql: () => import("@shikijs/langs/sql"),
	swift: () => import("@shikijs/langs/swift"),
	toml: () => import("@shikijs/langs/toml"),
	tsx: () => import("@shikijs/langs/tsx"),
	typescript: () => import("@shikijs/langs/typescript"),
	vue: () => import("@shikijs/langs/vue"),
	xml: () => import("@shikijs/langs/xml"),
	yaml: () => import("@shikijs/langs/yaml"),
};

export const bundledLanguages = {
	...languages,
	bash: languages["shellscript"],
	sh: languages["shellscript"],
	shell: languages["shellscript"],
	zsh: languages["shellscript"],
	"c++": languages["cpp"],
	"c#": languages["csharp"],
	cs: languages["csharp"],
	dockerfile: languages["docker"],
	gql: languages["graphql"],
	properties: languages["ini"],
	js: languages["javascript"],
	cjs: languages["javascript"],
	mjs: languages["javascript"],
	kt: languages["kotlin"],
	kts: languages["kotlin"],
	makefile: languages["make"],
	md: languages["markdown"],
	ps: languages["powershell"],
	ps1: languages["powershell"],
	pwsh: languages["powershell"],
	py: languages["python"],
	rb: languages["ruby"],
	rs: languages["rust"],
	ts: languages["typescript"],
	cts: languages["typescript"],
	mts: languages["typescript"],
	yml: languages["yaml"],
};

/** Unsupported syntax remains readable without asking the worker for an absent grammar. */
export function codeHighlightLanguage(language: string): string {
	const normalized = language.toLowerCase();
	return Object.hasOwn(bundledLanguages, normalized) ? normalized : "text";
}
