import type { UiLanguage } from "@ling/contracts/application";
import { Menu } from "electron";

const en = {
	about: "About Ling",
	quit: "Quit Ling",
	edit: "Edit",
	undo: "Undo",
	redo: "Redo",
	cut: "Cut",
	copy: "Copy",
	paste: "Paste",
	pasteAndMatchStyle: "Paste and Match Style",
	delete: "Delete",
	selectAll: "Select All",
	speech: "Speech",
	startSpeaking: "Start Speaking",
	stopSpeaking: "Stop Speaking",
	view: "View",
	reload: "Reload",
	forceReload: "Force Reload",
	toggleDevTools: "Toggle Developer Tools",
	resetZoom: "Actual Size",
	zoomIn: "Zoom In",
	zoomOut: "Zoom Out",
	togglefullscreen: "Toggle Full Screen",
	window: "Window",
	minimize: "Minimize",
	zoom: "Zoom",
	front: "Bring All to Front",
	close: "Close Window",
	showLing: "Show Ling",
	recentProjects: "Recent Projects",
};

export const nativeMenuCopy: Record<UiLanguage, typeof en> = {
	en,
	"zh-CN": {
		about: "关于 Ling",
		quit: "退出 Ling",
		edit: "编辑",
		undo: "撤销",
		redo: "重做",
		cut: "剪切",
		copy: "拷贝",
		paste: "粘贴",
		pasteAndMatchStyle: "粘贴并匹配样式",
		delete: "删除",
		selectAll: "全选",
		speech: "语音",
		startSpeaking: "开始朗读",
		stopSpeaking: "停止朗读",
		view: "显示",
		reload: "重新加载",
		forceReload: "强制重新加载",
		toggleDevTools: "开发者工具",
		resetZoom: "实际大小",
		zoomIn: "放大",
		zoomOut: "缩小",
		togglefullscreen: "切换全屏",
		window: "窗口",
		minimize: "最小化",
		zoom: "缩放",
		front: "前置全部窗口",
		close: "关闭窗口",
		showLing: "显示 Ling",
		recentProjects: "最近项目",
	},
	ja: {
		about: "Ling について",
		quit: "Ling を終了",
		edit: "編集",
		undo: "取り消す",
		redo: "やり直す",
		cut: "カット",
		copy: "コピー",
		paste: "ペースト",
		pasteAndMatchStyle: "ペーストしてスタイルを合わせる",
		delete: "削除",
		selectAll: "すべてを選択",
		speech: "スピーチ",
		startSpeaking: "読み上げを開始",
		stopSpeaking: "読み上げを停止",
		view: "表示",
		reload: "再読み込み",
		forceReload: "強制再読み込み",
		toggleDevTools: "開発者ツール",
		resetZoom: "実際のサイズ",
		zoomIn: "拡大",
		zoomOut: "縮小",
		togglefullscreen: "フルスクリーン切り替え",
		window: "ウインドウ",
		minimize: "最小化",
		zoom: "拡大／縮小",
		front: "すべてを手前に移動",
		close: "ウインドウを閉じる",
		showLing: "Ling を表示",
		recentProjects: "最近のプロジェクト",
	},
	ko: {
		about: "Ling 정보",
		quit: "Ling 종료",
		edit: "편집",
		undo: "실행 취소",
		redo: "다시 실행",
		cut: "잘라내기",
		copy: "복사",
		paste: "붙여넣기",
		pasteAndMatchStyle: "스타일 일치시켜 붙여넣기",
		delete: "삭제",
		selectAll: "모두 선택",
		speech: "말하기",
		startSpeaking: "말하기 시작",
		stopSpeaking: "말하기 중단",
		view: "보기",
		reload: "새로고침",
		forceReload: "강력 새로고침",
		toggleDevTools: "개발자 도구",
		resetZoom: "실제 크기",
		zoomIn: "확대",
		zoomOut: "축소",
		togglefullscreen: "전체 화면 전환",
		window: "윈도우",
		minimize: "최소화",
		zoom: "확대/축소",
		front: "모두 앞으로 가져오기",
		close: "윈도우 닫기",
		showLing: "Ling 표시",
		recentProjects: "최근 프로젝트",
	},
};

/** Explicit labels follow Ling's language; native roles retain OS actions and shortcuts. */
export function setDesktopMenuLanguage(language: UiLanguage): void {
	const copy = nativeMenuCopy[language];
	const mac = process.platform === "darwin";
	const role = (
		name: Exclude<Electron.MenuItemConstructorOptions["role"], undefined> & keyof typeof en,
	): Electron.MenuItemConstructorOptions => ({ role: name, label: copy[name] });
	const separator: Electron.MenuItemConstructorOptions = { type: "separator" };
	Menu.setApplicationMenu(
		Menu.buildFromTemplate([
			{ label: "Ling", submenu: [role("about"), separator, role("quit")] },
			{
				label: copy.edit,
				submenu: [
					role("undo"),
					role("redo"),
					separator,
					role("cut"),
					role("copy"),
					role("paste"),
					...(mac ? [role("pasteAndMatchStyle")] : []),
					role("delete"),
					role("selectAll"),
					...(mac ? [separator, { label: copy.speech, submenu: [role("startSpeaking"), role("stopSpeaking")] }] : []),
				],
			},
			{
				label: copy.view,
				submenu: [
					role("reload"),
					role("forceReload"),
					role("toggleDevTools"),
					separator,
					role("resetZoom"),
					role("zoomIn"),
					role("zoomOut"),
					separator,
					role("togglefullscreen"),
				],
			},
			{
				role: "windowMenu",
				label: copy.window,
				submenu: [role("minimize"), role("zoom"), ...(mac ? [separator, role("front")] : []), role("close")],
			},
		]),
	);
}
